---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
    exclude_fingerprints:
    - be3d978ddcf09368ef989d499ef01c81
ratings:
  paths:
  - "**.rb"
exclude_paths:
- spec/
